---

- name: upload build files   
  synchronize: src=docker-build dest=/tmp

- name: build nginx docker image
  docker_image:
    name: hello-adv-nginx-image
    tag: v1
    path: /tmp/docker-build
    state: present

- name: run nginx docker container
  docker:
    name: hello-adv-nginx-container
    image: "hello-adv-nginx-image:v1"
    command: rc-service nginx start
    publish_all_ports: yes
