---
# ansible-playbook --inventory hosts site.yml

- hosts: ci
  become: true
  become_user: root
  become_method: sudo

  roles:
  - { role: common, tags: "common" }
  - { role: nginx, tags: "nginx" }
  - { role: jenkins, tags: "jenkins" }

- hosts: deploy
  become: true
  become_user: root
  become_method: sudo

  roles:
  - { role: common, tags: "common" }
  - { role: nginx, tags: "nginx" }

