- name: upload jenkins build files
  copy:
    src: docker-build
    dest: /tmp/jenkins
    directory_mode: yes

- name: build jenkins docker image
  docker_image:
    name: hello-adv-jenkins-image
    tag: v1
    path: /tmp/jenkins/docker-build
    state: present
