---
- name: upload jenkins build files
  copy:
    src: docker-build
    dest: /tmp/jenkins
    directory_mode: yes

- name: build jenkins docker image
  docker_image:
    name: hello-adv-jenkins-image
    tag: v1
    path: /tmp/jenkins/docker-build
    state: present

- name: run jenkins docker container
  docker_container:
    name: hello-adv-jenkins-container
    image: "hello-adv-jenkins-image:v1"
    ports: 
      - 8080:8080
