---

- name: upload build files   
  synchronize: src=docker-build dest=/tmp/tomcat

- name: build tomcat docker image
  docker_image:
    name: hello-adv-tomcat-image
    tag: v1
    path: /tmp/tomcat/docker-build
    state: present

- name: run tomcat docker container
  docker_container:
    name: hello-adv-tomcat-container
    image: "hello-adv-tomcat-image:v1"
    ports: 
      - 8888:8080
